samples: "/data/NHLBI_IDSS/projects/NHLBI-4/samples.txt"
rawdata_dir: "/data/NHLBI_IDSS/rawdata/NHLBI-4/fastq"
result_dir: "/data/NHLBI_IDSS/projects/NHLBI-4"
hg38_fa: "/data/NHLBI_IDSS/references/Bismark_Genomes/hg38/genome.fa"
hg38_gtf: "/fdb/igenomes/Homo_sapiens/UCSC/hg38/Annotation/Genes/genes.gtf"
hg38_rRNA_intervals: "/data/NHLBI_IDSS/references/Bismark_Genomes/hg38/RNA-Seek_build/hg38.rRNA_interval_list"
hg38_refFlat: "/data/NHLBI_IDSS/references/Bismark_Genomes/hg38/RNA-Seek_build/refFlat.txt"
hg38_bed_ref: "/data/NHLBI_IDSS/references/Bismark_Genomes/hg38/RNA-Seek_build/genes.ref.bed"
mm10_fa: "/fdb/igenomes/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa"
rn6_fa: "/fdb/igenomes/Rattus_norvegicus/UCSC/rn6/Sequence/WholeGenomeFasta/genome.fa"
bisulphite_ref: "/data/NHLBI_IDSS/references/Bismark_Genomes"
bisulphite_fa: "/fdb/igenomes/Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/genome.fa"
phage_fa: "/data/NHLBI_IDSS/references/Bismark_Genomes/phage/genome.fa"
phage_ref: "/data/NHLBI_IDSS/references/Bismark_Genomes/phage"
species: "hg38"
REF_ATLAS: "/data/NHLBI_IDSS/references/MethylCpG_deconvolution/resources/reference_atlas.csv"
CpG_MAP_TABLE: "/data/NHLBI_IDSS/references/MethylCpG_deconvolution/resources/reference_atlas.hg38.unique.bed"
wgbsDir: "/data/OpenOmics/references/methyl-seek"
atlas_bed_hg38: "/data/OpenOmics/references/methyl-seek/UXM_deconv/supplemental/Atlas.U25.l4.hg38.bed"
atlas_tsv_hg38: "/data/OpenOmics/references/methyl-seek/UXM_deconv/supplemental/Atlas.U25.l4.hg38.tsv"
atlas_bed_hg19: "/data/OpenOmics/references/methyl-seek/UXM_deconv/supplemental/Atlas.U25.l4.hg19.bed"
atlas_tsv_hg19: "/data/OpenOmics/references/methyl-seek/UXM_deconv/supplemental/Atlas.U25.l4.hg19.tsv"
REF_MARKERS: "/data/NHLBI_IDSS/projects/NHLBI-4/cfDNAme_data/Atlas.MethylMatrix.markers_22cov.tsv"
REF_IDS: "/data/NHLBI_IDSS/projects/NHLBI-4/cfDNAme_data/reference_methylomes.20230803.tsv"
GOLD_MARKERS: "/data/NHLBI_IDSS/projects/NHLBI-4/cfDNAme_data/golden_markers.22.bed"
HG38TOHG19: "/data/NHLBI_IDSS/projects/NHLBI-4/cfDNAme_data/hg38ToHg19.over.chain.gz"
