name: docs
on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install --upgrade pip
      - run: pip install -r docs/requirements.txt
      - run: mkdocs gh-deploy --force
